services:
  postgres:
    image: postgres:15-alpine
    container_name: toktickit-postgres
    restart: always
    environment:
      POSTGRES_USER: toktickit
      POSTGRES_PASSWORD: toktickit
      POSTGRES_DB: toktickit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
